update to remove object3d mesh when component removed from entity
bryik/aframe-controller-cursor-component pull request #17
Opened 2017-06-04 06:08 UTC by kfarr

This PR is just a simple `remove` function that removes the cursor mesh when the component is removed from an entity. I also updated the dist to reflect these changes.

2017-06-04 23:39 UTC, bryik requested changes

2017-06-04 23:39 UTC, bryik commented on index.js
> +    cursorEl.removeObject3D('cursormesh');
Does `remove` detach event listeners? I think you might have to call `pause` manually.

2017-06-04 23:55 UTC, bryik commented
Also, kudos for working on this despite all the examples being broken with A-Frame 0.5.0! Maybe I should bump the dependency to A-Frame master as a stop-gap.

2017-06-05 05:36 UTC, kfarr commented on index.js
> +    cursorEl.removeObject3D('cursormesh');
Good question, it looks like `pause` is called by a-frame itself prior to `remove`. I tested this only with console log comments (it showed both pause and remove functions running when the component is removed), however I have not explicitly tested to see if the event listeners are still running upon removing the component.

2017-06-05 14:57 UTC, bryik commented on index.js
> +    cursorEl.removeObject3D('cursormesh');
> it looks like pause is called by a-frame itself prior to remove

Yes you're right, my mistake!

> I have not explicitly tested to see if the event listeners are still running

I'm going to trust that they are removed :smile:

2017-06-05 14:57 UTC, merged

2017-06-05 14:58 UTC, bryik commented
Thanks!